# Generated by Django 4.1.7 on 2023-03-25 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("date_opened", models.DateField()),
                (
                    "amount_opened_with",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("broker", models.CharField(max_length=50)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pair", models.CharField(max_length=10)),
                ("entry_date", models.DateTimeField()),
                ("exit_date", models.DateTimeField(blank=True, null=True)),
                ("lot", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_open", models.BooleanField()),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("spread", models.DecimalField(decimal_places=5, max_digits=10)),
                ("entry_price", models.DecimalField(decimal_places=5, max_digits=10)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                ("strategy", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=10)),
                ("is_profit", models.BooleanField()),
                ("risk_ratio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pips", models.IntegerField()),
                ("conviction", models.CharField(max_length=50)),
                ("time_frame", models.CharField(max_length=10)),
                ("is_tp_hit", models.BooleanField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trading_acct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.tradingaccount",
                    ),
                ),
            ],
        ),
    ]
