# Generated by Django 4.1.7 on 2023-03-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_journal_lot_alter_journal_pair_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="position",
            field=models.CharField(
                choices=[("LONG", "LONG"), ("SHORT", "SHORT")], max_length=10
            ),
        ),
    ]
